### ISSUE TITLE
Allow specifying custom mount options

### ISSUE THREAD

**Issue by Atrate** [Rudd-O/qubes-shared-folders#6]
It would be nice if there was an option to specify custom mount options. In the code, they could probably be appended to this line:

https://github.com/Rudd-O/qubes-shared-folders/blob/dc28314ffad31f2fcf435beff5d4a51de2643e17/py/sharedfolders/programs.py#L321

This may require some more advanced argument handling than in 
https://github.com/Rudd-O/qubes-shared-folders/blob/dc28314ffad31f2fcf435beff5d4a51de2643e17/py/sharedfolders/programs.py#L206

Either via writing a full, secure argument parser, using an external library like `argparse`, or using an environment variable like `QREXEC_MOUNT_OPTIONS` as a workaround

Use case: I want to be able to mount folders as read-only in certain qubes, to prevent accidental modification. For now, I work around it by bind-mounting it as read-only in the source qube and mounting the bind-mounted folder, not the original, but it's a tedious workaround.

**Comment by Rudd-O** [comment]
Mounting a folder read-only is not a security measure — if the client qube is compromised, then the read-only flag can easily be bypassed.

I think what you want is to export the shared folder as read-only from the perspective of the diod file server.  Your current workaround is acceptable even if cumbersome because it will cause diod to reject writes; I wish there was a better way.

Leaving the ticket open in case someone is interested.

**Comment by Rudd-O** [comment]
No attention to the matter has presented itself in a few months.  Closing.
